### ISSUE TITLE
could you please share the orgin dataset? thank you very much!

### ISSUE THREAD

**Issue by Value-Jack** [MitchFuchs/asbar#2]

**Comment by MitchFuchs** [comment]
Hi @Value-Jack, 

Thanks for your interest! 

You can download the original OpenMonkeyChallenge dataset here: https://competitions.codalab.org/competitions/34342#learn_the_details

As for PanAf, the dataset can be found here: https://obrookes.github.io/panaf.github.io/

Let me know if you need more assistance. 

Cheers, 
Mitch
